package launch;

import org.apache.commons.lang.StringEscapeUtils;

public class JavaPlayground {
	public static void main(String[] args) {
		System.out.println(StringEscapeUtils.unescapeXml("&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;Package xmlns=&quot;http://soap.sforce.com/2006/04/metadata&quot;&gt;&lt;types&gt;&lt;members&gt;SFChange&lt;/members&gt;&lt;name&gt;ApexClass&lt;/name&gt;&lt;/types&gt;&lt;types&gt;&lt;members&gt;Authenticated Website&lt;/members&gt;&lt;members&gt;Authenticated Website&lt;/members&gt;&lt;members&gt;Chatter External User&lt;/members&gt;&lt;members&gt;Chatter Free User&lt;/members&gt;&lt;members&gt;Chatter Moderator User&lt;/members&gt;&lt;members&gt;Contract Manager&lt;/members&gt;&lt;members&gt;Cross Org Data Proxy User&lt;/members&gt;&lt;members&gt;Custom: Marketing Profile&lt;/members&gt;&lt;members&gt;Custom: Sales Profile&lt;/members&gt;&lt;members&gt;Custom: Support Profile&lt;/members&gt;&lt;members&gt;Customer Community Login User&lt;/members&gt;&lt;members&gt;Customer Community User&lt;/members&gt;&lt;members&gt;Customer Portal Manager Custom&lt;/members&gt;&lt;members&gt;Customer Portal Manager Standard&lt;/members&gt;&lt;members&gt;Force&lt;/members&gt;&lt;members&gt;Force&lt;/members&gt;&lt;members&gt;Gold Partner User&lt;/members&gt;&lt;members&gt;High Volume Customer Portal&lt;/members&gt;&lt;members&gt;Identity User&lt;/members&gt;&lt;members&gt;Marketing User&lt;/members&gt;&lt;members&gt;Partner App Subscription User&lt;/members&gt;&lt;members&gt;Partner Community Login User&lt;/members&gt;&lt;members&gt;Partner Community User&lt;/members&gt;&lt;members&gt;Read Only&lt;/members&gt;&lt;members&gt;Silver Partner User&lt;/members&gt;&lt;members&gt;Solution Manager&lt;/members&gt;&lt;members&gt;Standard Guest&lt;/members&gt;&lt;members&gt;Standard Platform User&lt;/members&gt;&lt;members&gt;Standard User&lt;/members&gt;&lt;members&gt;System Administrator&lt;/members&gt;&lt;members&gt;Work&lt;/members&gt;&lt;name&gt;Profile&lt;/name&gt;&lt;/types&gt;&lt;version&gt;35.0&lt;/version&gt;&lt;/Package&gt;"));
		} 
}
